# Generated by Django 5.0.4 on 2025-03-17 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referee',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_articles', to='articles.referee'),
        ),
    ]
