# Generated by Django 5.0.4 on 2025-03-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_referee_articles_article_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='specialization',
            field=models.CharField(blank=True, help_text="Referee's area of expertise (e.g., Machine Learning, Data Science)", max_length=255),
        ),
    ]
