# Generated by Django 5.0.4 on 2025-03-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_anonymization_map_article_anonymized_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anonymization_key',
            field=models.CharField(blank=True, help_text='Encryption key for anonymization', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='anonymization_map',
            field=models.TextField(blank=True, help_text='JSON mapping of original text to encrypted text', null=True),
        ),
    ]
