# Generated by Django 5.0.4 on 2025-03-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extracted_emails',
            field=models.TextField(blank=True, help_text='Automatically extracted email addresses', null=True),
        ),
    ]
